apiVersion: v1
kind: Service
metadata:
  name: apiparkingEvent-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: apiparkingEvent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
