apiVersion: v1
kind: Service
metadata:
  name: apiparkingevent-service
  namespace: smart-parking
spec:
  type: NodePort
  selector:
    app: apiparkingevent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
