apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: smart-parking
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/er4ikk/smart-parking-db:latest
        resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "800m"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-pv-volume
          mountPath: /var/lib/postgres_data
      volumes:
      - name: postgres-pv-volume
        persistentVolumeClaim:
          claimName: postgres-pv-claim