apiVersion: apps/v1

kind: Deployment

metadata:
  name: smart-parking-portal
  namespace: smart-parking
  labels:
    app: smart-parking-portal

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smart-parking-portal

  template:
    metadata:
      labels:
        app: smart-parking-portal

    spec:
      containers:
        - name: smart-parking-portal

          image: docker.io/er4ikk/smart-parking-portal
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"

          ports:
            - containerPort: 80
