apiVersion: v1
kind: Service
metadata:
  name: smart-parking-portal-service
  namespace: acmeat
spec:
  type: NodePort
  selector:
    app: smart-parking-portal
  ports:
    - protocol: TCP
      port: 4201
      targetPort: 80
